import 'echarts/lib/chart/bar'
import 'echarts/lib/chart/boxplot'
import 'echarts/lib/chart/candlestick'
import 'echarts/lib/chart/chord'
import 'echarts/lib/chart/effectScatter'
import 'echarts/lib/chart/funnel'
import 'echarts/lib/chart/gauge'
import 'echarts/lib/chart/graph'
import 'echarts/lib/chart/heatmap'
import 'echarts/lib/chart/line'
import 'echarts/lib/chart/lines'
import 'echarts/lib/chart/map'
import 'echarts/lib/chart/parallel'
import 'echarts/lib/chart/pie'
import 'echarts/lib/chart/radar'
import 'echarts/lib/chart/sankey'
import 'echarts/lib/chart/scatter'
import 'echarts/lib/chart/sunburst'
import 'echarts/lib/chart/themeRiver'
import 'echarts/lib/chart/tree'
import 'echarts/lib/chart/treemap'
import 'echarts/dist/extension/bmap.js'

import 'echarts/lib/component/tooltip'
import 'echarts/lib/component/toolbox'
import 'echarts/lib/component/legend'
import 'echarts/lib/component/title'
import 'echarts/lib/component/geo'
import 'echarts/lib/component/visualMap'
import 'echarts/map/js/china.js';

export default {};
